services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: permterm_frontend_prod_image:latest
    container_name: permterm_frontend_prod
    command: sh -c "npm run start"
    restart: always
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx                
      dockerfile: Dockerfile.prod
    container_name: permterm_nginx_prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/ssl:/etc/nginx/ssl:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge