# Build frontend
FROM node:18-alpine AS frontend-build

WORKDIR /app

COPY ./package*.json .
RUN npm install

COPY . .

RUN chmod +x node_modules/.bin/vite
RUN npm run build

# Nginx
FROM nginx:1.27.4

RUN rm /etc/nginx/conf.d/default.conf

COPY /nginx/nginx_prod.conf /etc/nginx/conf.d/nginx_prod.conf

COPY --from=frontend-build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
