import { Footer } from '@/widgets/footer';
import { Header } from '@/widgets/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Object',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='bg-[radial-gradient(circle_at_center,_#272826_0%,_#141513_100%)]'>
      <Header />
      <main>
        {children}
      </main>
      {/* <Footer /> */}
    </div>
  );
}
