import { Footer } from '@/widgets/footer';
import { Header } from '@/widgets/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Объект',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='bg-[linear-gradient(to_right,_#141513,_#272826,_#141513)]'>
      <Header />
      <main>
        {children}
      </main>
      <Footer />
    </div>
  );
}
